select top 20 *
from Customer_Behaviour..customer

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) AS revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where subscription_status = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS average_product_rating
from customer
group by item_purchased
order by AVG(review_rating) DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, ROUND(AVG(CAST(purchase_amount AS FLOAT)),2) as average_purchase_amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, COUNT(customer_id) AS total_customers, ROUND(AVG(CAST(purchase_amount AS FLOAT)),2) as average_spent, ROUND(SUM(CAST(purchase_amount AS DECIMAL(10,2))),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spent DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,
CAST(ROUND(100.0 * SUM(CASE
		WHEN discount_applied = 'Yes' THEN 1 ELSE 0
	END) / COUNT(*),2) AS decimal(10,2)) 
	AS discount_rate
from customer
group by item_purchased
order by discount_rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, COUNT(*) AS number_of_customer
from customer_type
group by customer_segment
order by number_of_customer DESC

--Q8. What are the top 3 most purchased products within each category? 

with item_count as (
select category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by COUNT(customer_id) DESC) AS item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) AS repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group,
SUM(purchase_amount) AS total_revenue
from customer
group by age_group
order by total_revenue DESC